Repository haeun-i/CodingTest, pull requests merged in 2022-08, with the labels that each got.

#3 [1주차] : BOJ 2638 / 치즈 / 골드 3
  KSH/BOJ_2638.cpp
Labels: 너비 우선 탐색, 구현

#1 [1주차] : BOJ 11779 / 최소비용 구하기 2 / 골드 3
  KSH/BOJ_11779.cpp
Labels: 다익스트라

#4 [1주차] : BOJ 1932 / 정수 삼각형 / 실버 1
  KES/BOJ_1932.cpp
Labels: 다이나믹 프로그래밍

#2 [1주차] : BOJ 1874 / 스택 수열 / 실버 3
  KES/BOJ_1874.cpp
Labels: 스택

#5 [1주차] : BOJ 1697 / 숨바꼭질 / 실버 1
  KHE/BOJ_1697.cpp
Labels: 깊이 우선 탐색

#6 [1주차] : BOJ 10026 / 적록색약 / 골드 5
  KHE/BOJ_10026.cpp
Labels: 너비 우선 탐색

#12 [2주차] : BOJ 7576 / 토마토 / 골드 5
  KHE/BOJ_7576.cpp
Labels: 너비 우선 탐색

#10 [2주차] : BOJ 7579 / 앱 / 골드 3
  KSH/BOJ_7579.cpp
Labels: 다이나믹 프로그래밍

#8 [2주차] : BOJ 13460 / 구슬 탈출 2 / 골드 1
  KSH/BOJ_13460.cpp
Labels: 너비 우선 탐색, 구현, 깊이 우선 탐색

#9 [2주차] : BOJ 1992 / 쿼드트리 / 실버 1
  KHE/BOJ_1992.cpp
Labels: 분할정복

#7 [2주차] BOJ 1629 / 곱셈 / 실버 1
  KES/BOJ_1629.cpp
Labels: 분할정복

#11 [2주차] : BOJ 1149/ RGB거리 / 실버 1
  KES/BOJ_1149.cpp
Labels: 다이나믹 프로그래밍
