Repository haeun-i/CodingTest, pull requests merged in 2022-09, with the labels that each got.

#15 [3주차] : BOJ 11052 / 카드 구매하기 / 실버 1
  KHE/BOJ_11052.cpp
Labels: 다이나믹 프로그래밍

#16 [3주차] : BOJ 1182 / 부분수열의 합 / 실버 2
  KHE/BOJ_1182.cpp
Labels: 백트래킹

#17 [3주차] : BOJ 1002 / 터렛 / 실버 3
  KES/BOJ_1002.cpp
Labels: 기하학

#18 [3주차] : BOJ 1756 / 피자 굽기 / 골드 5
  KES/BOJ_1756.cpp
Labels: 구현

#14 [3주차] : BOJ 1005 / ACM Craft / 골드 3
  KSH/BOJ_1005.cpp
Labels: 다이나믹 프로그래밍, 위상 정렬

#13 [3주차] : BOJ 9328 / 열쇠 / 골드 1
  KSH/BOJ_9328.cpp
Labels: 너비 우선 탐색, 구현

#23 [4주차] : BOJ 2098 / 외판원 순회 / 골드 1
  KSH/BOJ_2098.cpp
Labels: 다이나믹 프로그래밍

#24 [4주차] : BOJ 2239 / 스도쿠 / 골드 4
  KSH/BOJ_1197.cpp
  KSH/BOJ_2239.cpp
Labels: 백트래킹

#20 [4주차] : BOJ 1759 / 암호 만들기 / 골드 5
  KHE/BOJ_1759.cpp
Labels: 백트래킹

#19 [4주차] : BOJ 14719 / 빗물 / 골드 5
  KHE/BOJ_14719.cpp
Labels: 구현

#22 [4주차] : BOJ 1527/ 금민수의 개수 / 실버 1
  KES/BOJ_1527.cpp
Labels: 깊이 우선 탐색

#21 [4주차] : BOJ 1564/ 팩토리얼5 / 실버 2
  KES/BOJ_1564.cpp
Labels: 수학, 정수론

#28 [5주차] : BOJ 9252 / LCS 2 / 골드 4
  KSH/BOJ_9252.cpp
Labels: 다이나믹 프로그래밍

#27 [5주차] : BOJ 12015/ 가장 긴 증가하는 부분 수열 2 / 골드 2
  KSH/BOJ_12015.cpp
Labels: 이분 탐색
